esphome:
  name: apollo-multisensor-mk1
  friendly_name: Apollo Multisensor Mk1
  comment: Apollo Multisensor Mk1
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

  on_boot:
    priority: 900
    then:
      - lambda: |-
          id(cpu_speed) = ESP.getCpuFreqMHz() ;
      

  project:
    name: "Apollo.Multisensor"
    version: "Mk1"

  min_version: 2023.6.1

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
  #board: featheresp32-s2

globals:
  - id: cpu_speed
    type: int
    restore_value: no
    initial_value: "0"

# Enable Home Assistant API
api:
  #encryption:
  #  key: "Csv8khdaMzNQyVYMYVpCfcDFHXiJYiYjZ+KMY8g4xF4="

logger:

ota:
  password: "apolloautomation"

wifi:
  ssid: "Schirmer-IoT" #!secret wifi_ssid
  password: "Apollo1359!" #!secret wifi_password
  power_save_mode: NONE

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Apollo Multisensor Hotspot"
    password: ""

captive_portal:

web_server:
  port: 80

i2c:
  sda: 4
  scl: 5
  id: bus_a

binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
ld2410:
  timeout: 150s
  max_move_distance : 6m
  max_still_distance: 0.75m
  id: ld2410_radar

sensor:
  - platform: template
    name: "ESP Cpu Speed"
    accuracy_decimals: 0
    unit_of_measurement: Mhz
    lambda: |-
      return (id(cpu_speed));
    entity_category: "diagnostic"

  - platform: template
    id: sys_esp_temperature
    name: ESP Temperature
    lambda: return temperatureRead();
    unit_of_measurement: °C
    device_class: TEMPERATURE
    update_interval: 30s

  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 10s

  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: "kB"
    state_class: measurement
    entity_category: "diagnostic"

  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 5s
    entity_category: "diagnostic"

  - platform: scd4x
    co2:
      name: "CO2"
      id: "co2"
    temperature:
      name: SCD40 Temperature
      id: scd40temperature
    humidity:
      name: SCD40 Humidity
      id: scd40humidity
    automatic_self_calibration: false
    update_interval: 10s
    measurement_mode: "periodic"
    address: 0x62
    i2c_id: bus_a
  - platform: ld2410
    moving_distance:
      name : Moving Distance
      id: moving_distance
    still_distance:
      name: Still Distance
      id: still_distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance




#light:
#  - platform: neopixelbus
#    type: GRB
#    variant: WS2811
#    pin: 3
#    num_leds: 1
#    name: "NeoPixel Light"

uart:
  tx_pin: GPIO0
  rx_pin: GPIO1
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

time:
  - platform: sntp
    id: time_sntp

button:
  #- platform: template
  #  name: "Enable LD2410 BLE"
  #  # disabled_by_default: True
  #  entity_category: "config"
  #  icon: mdi:bluetooth
  #  on_press:
  #    lambda: |-
  #      id(ld2410_radar) -> ble_control(true);
#
  #- platform: template
  #  name: "Disable LD2410 BLE"
  #  # disabled_by_default: True
  #  entity_category: "config"
  #  icon: mdi:bluetooth-off
  #  on_press:
  #    lambda: |-
  #      id(ld2410_radar) -> ble_control(false);
#
  #- platform: template
  #  name: "LD2410 Reboot"
  #  icon: mdi:radar
  #  entity_category: "config"
  #  on_press:
  #    lambda: |-
  #      // auto* radar = LD2410Component::get(ld2410); 
  #      // radar -> roboot();
  #      id(ld2410_radar) -> reboot();

  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"

  - platform: factory_reset
    disabled_by_default: True
    name: Factory Reset
    id: factory_reset_all
